# Generated by Django 2.0.2 on 2018-02-24 17:33

from django.db import migrations, models
import django.db.models.deletion
import ttt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ttt', '0002_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('grid', ttt.fields.ListField()),
                ('winner', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=256)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttt.User'),
        ),
    ]
