# Generated by Django 2.0.2 on 2018-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0004_auto_20180225_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='grid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
