# Generated by Django 2.0.2 on 2018-02-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0005_auto_20180225_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default=' ', max_length=1),
        ),
    ]
